### ISSUE TITLE
Code Refactoring/Performance Enhancer

### ISSUE THREAD

**Issue by livxy** [ProtDos/boosint#2]
Hey! I really like this a lot, would it be okay to have your permission to make a PR for code refactoring, I can also make the code a bit faster possibly. 

_(The reason I'm asking is that some people dislike it when others refactor)_

**Comment by ProtDos** [comment]
Hi. I'd really appreciate a PR. You can do it if you want.

**Comment by ProtDos** [comment]
> Hey! I really like this a lot, would it be okay to have your permission to make a PR for code refactoring, I can also make the code a bit faster possibly.
> 
> _(The reason I'm asking is that some people dislike it when others refactor)_

I saw your forked repo, when you are done you can ofc pull request it. I'd appreciate it.
